trigger:
- dev
- qa

pool:
  vmImage: ubuntu-latest

steps:

- publish: '$(System.DefaultWorkingDirectory)'
  artifact: vehicles

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm run lint
    npm run build
  displayName: Npm commands